AllCops:
  Exclude:
    - db/schema.rb
  RunRailsCops: true

HashSyntax:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Rails/Output:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    inject: 'inject'

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/Not:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%Q': '[]'
    '%W': '[]'
    '%i': '[]'
    '%q': '[]'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%x': '[]'

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false
