language: ruby

rvm:
  - 1.9.3
  - 2.0.0

env:
  - DB=mysql
  - DB=postgresql

before_script:
  - curl -Lo config/database.yml http://git.io/YLiX3g
  - bundle --quiet
  - bundle exec rake db:setup

script:
  - RAILS_ENV=test bundle exec rspec spec
