bundler_args: --without development production

before_script:
  - curl --silent -L https://gist.githubusercontent.com/BM5k/38c55d9ffaf6f9865949/raw/database.yml -o config/database.yml
  - bundle exec rake db:setup

cache: bundler

env:
  matrix:
    - DB=mysql
    - DB=postgresql
    - DB=sqlite

language: ruby

rvm:
  - 2.1.6
  - 2.2.2

script: RAILS_ENV=test bundle exec rake spec
sudo:   false
